import { Raleway, Assistant } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const raleway = Raleway({
    subsets: ["latin"],
    variable: '--font-raleway',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

const assistant = Assistant({
    subsets: ["latin"],
    variable: '--font-assistant',
    weight: ['200', '300', '400', '500', '600', '700', '800']
})


export const metadata = {
  title: "DD Commodities",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} ${assistant.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
